export const BOOK_REQUEST_PENDING = "BOOK_REQUEST_PENDING";
export const BOOK_REQUEST_FAILURE = "BOOK_REQUEST_FAILURE";
export const BOOK_REQUEST_SUCCESS = "BOOK_REQUEST_SUCCESS";

export const EDIT_REQUEST_SUCCESS = "EDIT_REQUEST_SUCCESS";
